### ISSUE TITLE
Is there something like combine latest?

### ISSUE THREAD

**Issue by nichoth** [pull-stream/pull-stream-faq#2]
Is there a way to do the [combineLatest](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/combinelatest.md#rxobservablecombinelatestargs-resultselector) algorithm like in rxjs? This is different from the existing `pull-zip` function.

I made my own btw: [pull-combine-latest](https://github.com/nichoth/pull-combine-latest)  :)

**Comment by dominictarr** [comment]
cool, can you make a PR to add it to https://github.com/pull-stream/pull-stream-docs +

**Comment by nichoth** [comment]
Thanks dominictarr
